#!/bin/bash
if [ -z "$1" ]; then
    echo "source docker-machine-activate <machine-name>"
    return 1
fi

MACHINE_NAME=$1

docker-machine env $MACHINE_NAME &> /dev/null
EXIT_CODE=$?

if [ ! $EXIT_CODE -eq 0 ]; then
    echo "Cannot connect to $MACHINE_NAME, check docker-machine env $MACHINE_NAME"
    return 1
fi

deactivate(){
    eval $(docker-machine env -u)
    PS1="$OLD_PS1"
    unset OLD_PS1

    if [ ! "$1" = "nondestructive" ]; then
        unset -f deactivate
    fi
}

if [ -n "$OLD_PS1" ]; then
    deactivate nondestructive
fi

eval $(docker-machine env $MACHINE_NAME)
OLD_PS1="$PS1"
PS1="($MACHINE_NAME) $PS1"
